language: cpp

compiler:
  - gcc

notifications:
  email: false

branches:
  only:
    - master
    - develop
    - "/^[0-9]+\\.[0-9]+\\.[0-9]+/"

services:
  - docker

before_install:
  - docker pull wurstmeister/zookeeper
  - docker pull wurstmeister/kafka
  - docker pull redborder/dev-containers:events-counter
  - pip install --user cpp-coveralls

install:
  - docker network create --subnet=172.26.0.0/24 test
  - >
    docker run -d --net test --ip 172.26.0.2 --name zookeeper
    wurstmeister/zookeeper
  - >
    docker run -d --net test --ip 172.26.0.3 --name kafka
    -e KAFKA_ADVERTISED_HOST_NAME="172.26.0.3" -e KAFKA_ADVERTISED_PORT="9092"
    -e KAFKA_ZOOKEEPER_CONNECT="172.26.0.2:2181" wurstmeister/kafka

script:
  - >
    docker run -v $(pwd):/app redborder/dev-containers:events-counter
    ./configure
  - docker run -v $(pwd):/app redborder/dev-containers:events-counter make
  - >
    docker run -v $(pwd):/app --net test -e CFLAGS=-w
    --link kafka redborder/dev-containers:events-counter make checks -j4

after_success:
  - docker run -v $(pwd):/app redborder/dev-containers:events-counter make clean
  - >
    docker run -v $(pwd):/app redborder/dev-containers:events-counter
    ./configure --enable-coverage
  - >
    docker run -v $(pwd):/app -e CFLAGS=-w --link kafka --net test
    redborder/dev-containers:events-counter make coverage
  - coveralls --exclude /usr/lib --exclude tests --gcov-options '\-lp'
